version: 2
jobs:
  build:
    docker:
      - image: brainpower/reason-from-the-very-beginning-dev
    working_directory: /root/repo
    steps:
      - checkout:
          path: /root/checkout
      - run:
          name: Sync
          command: cp -rf /root/checkout/* /root/repo
      - run:
          name: Install
          command: yarn
      - run:
          name: Compile dependencies
          command: yarn bsb -- -make-world
      - run:
          name: Compile
          command: yarn bsb
      - run:
          name: Test
          command: yarn jest