version: 2
jobs:
  build:
    docker:
      - image: brainpower/reason-from-the-very-beginning-dev
    working_directory: /repo
    steps:
      - checkout:
          path: ~/checkout
      - run:
          name: Sync
          command: cp -rf ~/checkout/* /repo/
      - run:
          name: Install
          command: yarn
      - run:
          name: Compile dependencies
          command: yarn bsb  -make-world
      - run:
          name: Compile
          command: yarn bsb
      - run:
          name: Test
          command: yarn jest